name: rybu
version: '0.1.0.0'
synopsis: Dedan preprocessor
description: Generates Dedan model from imperative code
author: Maciej Bielecki
maintainer: mbieleck@stud.elka.pw.edu.pl
copyright: 2016 Maciej Bielecki
license: BSD3
homepage: http://zyla.neutrino.re/rybu/

dependencies:
- base >=4.7 && <5
- containers

default-extensions:
- RecordWildCards
- LambdaCase
- TupleSections

library:
  source-dirs: src
  dependencies:
  - parsec
  - mtl

executables:
  rybu:
    main: Main.hs
    source-dirs: app
    dependencies:
    - rybu

tests:

  hspec-tests:
    main: Spec.hs
    source-dirs: test
    default-extensions:
    - TemplateHaskell
    - QuasiQuotes
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - rybu
    - hspec
    - HUnit
    - raw-strings-qq
    - parsec

  examples-test:
    main: ExamplesTest.hs
    source-dirs: test
    dependencies:
    - rybu
    - directory
    - process
    - filepath
